### ISSUE TITLE
使用他转发gitea后,后台开始疯狂刷报错

### ISSUE THREAD

**Issue by a810587921** [yosebyte/passport#1]
![image](https://github.com/user-attachments/assets/5ccbea00-c317-42d2-a52d-5194891c60f5)

服务端运行指令:

docker run --rm -d --network host ghcr.io/yosebyte/passport server://:10183/:10283

客户端运行参数:
client://服务端:10183/127.0.0.1:33000

**Comment by a810587921** [comment]
![image](https://github.com/user-attachments/assets/288bac5f-603e-492e-b0f8-e36d9a9e8c24)
复现成功了,使用域名访问时gitea提示这个,然后开始疯狂刷提示

**Comment by yosebyte** [comment]
@a810587921 感谢您的使用反馈，首先对出现的问题向您表达歉意，在处理之前跟您确认下问题：
- 您使用的时穿透模式；
- 客户端33000端口自建gitea服务；
- 您想通过服务端10283端口访问以上服务；
- 且通过指向服务端的域名访问时服务端也会出现`Unable to accept connections form link address`错误。
> 与此同时，请稍安勿躁，正在调查这项问题，请耐心等待，有进展第一时间回复。

**Comment by yosebyte** [comment]
初步判断是重连环节的锅，加log系统时把之前的feature改成了bug，正在修复。

**Comment by yosebyte** [comment]
问题已解决，推荐使用v1.1.4，若仍有问题请在此评论。
